version: "3.8"

services:
    fastapi:
        build: .
        volumes:
            - .:/bgrm_DeepLabV2/
        ports: 
            - "8888:80"
        links: 
            - mongodb
        deploy:
            resources:
                reservations:
                    devices:
                    - capabilities: [gpu]
          
        restart: always
        
    mongodb:
        image : mongo:latest
        hostname: mongodb
        environment:
            - MONGO_INITDB_DATABASE=image_db
            - MONGO_INITDB_ROOT_USERNAME=root
            - MONGO_INITDB_ROOT_PASSWORD=pass
        volumes:
            - ./mongodb/init-db.js:/docker-entrypoint-initdb.d/init-db.js:ro
        ports:
            - 27017:27017
        restart: always
